#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"

echo "Starting Repertory."

#exec \
#	s6-setuidgid abc /app/repertory/repertory -o uid=${PUID},gid=${PGID},big_writes /mnt/repertory && \
#	tail -f /dev/null

exec \
	s6-setuidgid abc tail -f /dev/null
