#!/usr/bin/with-contenv bash

# copy config
[[ ! -e /config/config.json ]] && \
	/app/repertory -gc
#	cp /defaults/config.json /config/config.json
	
chown -R abc:abc /config

# permissions
chown -R abc:abc \
	/config
