#!/usr/bin/with-contenv bash

echo "Check config exists."
if [ ! -e "/config/.local/repertory/sia/config.json" ]; then
	echo "Config does not exists so we create one."
	/app/repertory/repertory -gc
fi

usermod -a -G sudo abc

# permissions
chown -R abc:abc \
	/config
